name: ArchLinux

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PACKAGER: "Ni Lab <niharvardlab@gmail.com>"

jobs:
  build-libnacs:
    name: Build libnacs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v4
      - name: Initialize ArchLinux
        run: |
          bash github/setup-archlinux.sh
          chown -R user .
      - name: Setup ArchLinux CN repo
        # For sleef
        run: |
          bash github/setup-archlinux-cn.sh
      - name: Create package
        run: |
          cd arch/libnacs-git
          MAKEFLAGS="-j$(nproc)" sudo -u user makepkg -si --noconfirm
          rm -v *.log

      - name: "Upload binaries"
        uses: actions/upload-artifact@v4
        with:
          name: libnacs-git-package-archlinux
          path: ${{github.workspace}}/arch/libnacs-git/*.pkg.*

  build-python-libnacs:
    name: Build python-libnacs
    needs: build-libnacs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v4
      - name: Initialize ArchLinux
        run: |
          bash github/setup-archlinux.sh
          chown -R user .
      - name: Setup ArchLinux CN repo
        # For sleef
        run: |
          bash github/setup-archlinux-cn.sh

      - name: Download libnacs
        uses: actions/download-artifact@v4
        with:
          name: libnacs-git-package-archlinux
          path: libnacs-package

      - name: Create package
        run: |
          cd arch/python-libnacs-git
          pacman -U ../../libnacs-package/*.pkg.*
          MAKEFLAGS="-j$(nproc)" sudo -u user makepkg -si --noconfirm
          rm -v *.log

      - name: "Upload binaries"
        uses: actions/upload-artifact@v4
        with:
          name: python-libnacs-git-package-archlinux
          path: ${{github.workspace}}/arch/python-libnacs-git/*.pkg.*

  build-molecube2:
    name: Build molecube2
    needs: build-libnacs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v4
      - name: Initialize ArchLinux
        run: |
          bash github/setup-archlinux.sh
          chown -R user .
      - name: Setup ArchLinux CN repo
        # For sleef
        run: |
          bash github/setup-archlinux-cn.sh

      - name: Download libnacs
        uses: actions/download-artifact@v4
        with:
          name: libnacs-git-package-archlinux
          path: libnacs-package

      - name: Create package
        run: |
          cd arch/molecube2-git
          pacman -U ../../libnacs-package/*.pkg.*
          MAKEFLAGS="-j$(nproc)" sudo -u user makepkg -si --noconfirm
          rm -v *.log

      - name: "Upload binaries"
        uses: actions/upload-artifact@v4
        with:
          name: molecube2-git-package-archlinux
          path: ${{github.workspace}}/arch/molecube2-git/*.pkg.*

  build-labctrl-node:
    name: Build labctrl-node
    needs: build-libnacs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v4
      - name: Initialize ArchLinux
        run: |
          bash github/setup-archlinux.sh
          chown -R user .
      - name: Setup ArchLinux CN repo
        # For sleef
        run: |
          bash github/setup-archlinux-cn.sh

      - name: Download libnacs
        uses: actions/download-artifact@v4
        with:
          name: libnacs-git-package-archlinux
          path: libnacs-package

      - name: Create package
        run: |
          cd arch/labctrl-node-git
          pacman -U ../../libnacs-package/*.pkg.*
          MAKEFLAGS="-j$(nproc)" sudo -u user makepkg -si --noconfirm
          rm -v *.log

      - name: "Upload binaries"
        uses: actions/upload-artifact@v4
        with:
          name: labctrl-node-git-package-archlinux
          path: ${{github.workspace}}/arch/labctrl-node-git/*.pkg.*

  build-libspcm:
    name: Build libspcm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v4
      - name: Initialize ArchLinux
        run: |
          bash github/setup-archlinux.sh
          chown -R user .
      - name: Create package
        run: |
          cd arch/libspcm
          MAKEFLAGS="-j$(nproc)" sudo -u user makepkg -si --noconfirm
          rm -v *.log

      - name: "Upload binaries"
        uses: actions/upload-artifact@v4
        with:
          name: libspcm-package-archlinux
          path: ${{github.workspace}}/arch/libspcm/*.pkg.*
