name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download ArchLinux packages
      uses: dawidd6/action-download-artifact@v10
      with:
        workflow: archlinux.yml
        workflow_conclusion: success
        branch: master

    - name: Download ArchLinuxARM packages
      uses: dawidd6/action-download-artifact@v10
      with:
        workflow: archlinux-arm.yml
        workflow_conclusion: success
        branch: master

    - name: Download MSYS2 packages
      uses: dawidd6/action-download-artifact@v10
      with:
        workflow: msys2.yml
        workflow_conclusion: success
        branch: master

    - name: Download Ubuntu packages
      uses: dawidd6/action-download-artifact@v10
      with:
        workflow: ubuntu.yml
        workflow_conclusion: success
        branch: master

    - name: Install dependencies
      run: sudo apt-get install tar zip zstd

    - name: Create archlinux package tarball
      run: |
        mkdir archlinux-packages
        mv *-package-archlinux/*.pkg.tar.* archlinux-packages/
        tar -cvf archlinux-packages.tar.zst --zstd archlinux-packages/

    - name: Create archlinux-arm package tarball
      run: |
        mkdir archlinux-arm-packages
        mv *-package-archlinux-arm/*.pkg.tar.* archlinux-arm-packages/
        tar -cvf archlinux-arm-packages.tar.zst --zstd archlinux-arm-packages/

    - name: Create msys2 package tarball
      run: |
        mkdir msys2-packages
        mv mingw-*-package-msys2/*.pkg.tar.* msys2-packages/
        zip -r msys2-packages.zip msys2-packages/

    - name: Create ubuntu package tarball
      run: |
        mkdir ubuntu-20.04-packages
        mv *-package-ubuntu-20.04/*.deb ubuntu-20.04-packages/
        tar -cvf ubuntu-20.04-packages.tar.zst --zstd ubuntu-20.04-packages/

        mkdir ubuntu-22.04-packages
        mv *-package-ubuntu-22.04/*.deb ubuntu-22.04-packages/
        tar -cvf ubuntu-22.04-packages.tar.zst --zstd ubuntu-22.04-packages/

        mkdir ubuntu-24.04-packages
        mv *-package-ubuntu-24.04/*.deb ubuntu-24.04-packages/
        tar -cvf ubuntu-24.04-packages.tar.zst --zstd ubuntu-24.04-packages/

    - name: Tag release
      uses: ncipollo/release-action@v1
      with:
        artifacts: archlinux-packages.tar.zst,archlinux-arm-packages.tar.zst,msys2-packages.zip,ubuntu-20.04-packages.tar.zst,ubuntu-22.04-packages.tar.zst,ubuntu-24.04-packages.tar.zst
        body: Packages
        token: ${{ secrets.GITHUB_TOKEN }}
